import {Subsidiary} from "../models";
export class People {
    id: number;
    primerNombre: string;
    segundoNombre: string;
    primerApellido: string;
    segundoApellido: string;
    documento: string;
    ruc: string;
    fechaNacimiento: any;
    tipoPersona: string;
    sexo: string;
    numeroHijos: number;
    numeroDependientes: number;
    estadoCivil: string;
    separacionBienes: boolean;
    email: string;
    telefonoParticular: string;
    telefonoSecundario: string;
    direccionParticular: string;
    direccionDetallada: string;
    observacion: string;
    latitud: number;
    longitud: number;
    sucursal: Subsidiary = new Subsidiary;
    activo: string;
    nacionalidad: any;
    pais: any;
    departamento: any;
    ciudad: any;
    barrio: any;
    imagePath: string;
    avatar: string|any;
}
